name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - main
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: heekah/quartz:v4
    steps:
      - uses: actions/checkout@v4
        with:
          path: content
          fetch-depth: 1
      - name: Build Quartz
        run: |
          cd /usr/src/app/
          cp $GITHUB_WORKSPACE/content/.quartz/* ./
          npx quartz build -d $GITHUB_WORKSPACE/content -o $GITHUB_WORKSPACE/public
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      volumes:
        - public:${{ github.workspace }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

